# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=4)),
                ('director', models.CharField(max_length=100)),
                ('plot', models.CharField(max_length=1500)),
                ('poster', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(default='password', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='moviebacklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.User'),
        ),
    ]
