# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20171128_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviebacklog',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviebacklog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MovieBacklog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
