# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0005_moviebacklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateField(default=datetime.datetime(2017, 12, 10, 16, 26, 7, 400229))),
                ('date', models.DateTimeField()),
                ('list_size', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
