# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_auto_20171210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienight',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 10, 16, 35, 40, 256262)),
        ),
    ]
