# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_auto_20171210_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movienight',
            name='date',
        ),
        migrations.AlterField(
            model_name='movienight',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 16, 40, 9, 72873)),
        ),
    ]
