# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0017_auto_20171210_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movienight',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
